//! Deno/V8 JS runtime — isolated inside a `cdylib`.
//!
//! This is the *only* crate in the workspace that imports `deno_core`.
//! Everything crosses the ABI boundary as UTF-8 JSON strings, keeping V8
//! entirely out of `sapphillon_core`'s compile graph.
//!
//! # Ops registered in the runtime
//!
//! | Op name                  | Purpose                                      |
//! |--------------------------|----------------------------------------------|
//! | `op_sapphillon_dispatch` | Route any plugin call to `PluginDispatcher`  |
//! | `op_capture_stdout`      | Store `console.*` output for capture mode    |

use std::cell::RefCell;

use abi_stable::{
    export_root_module,
    prefix_type::PrefixTypeTrait,
    std_types::{RErr, ROk, RResult, RStr, RString, RVec},
};
use deno_core::{op2, Extension, FastString, JsRuntime, OpDecl, OpState, RuntimeOptions};
use sapphillon_deno_interface::{JsEngineLib, JsEngineLibRef, PluginDispatcher};

// ── Root module export ────────────────────────────────────────────────────

#[export_root_module]
pub fn get_root_module() -> JsEngineLibRef {
    JsEngineLib { run_script: ffi_run_script }.leak_into_prefix()
}

// ── FFI entry point ───────────────────────────────────────────────────────

extern "C" fn ffi_run_script(
    script: RStr<'_>,
    pre_scripts: RVec<RString>,
    dispatcher: PluginDispatcher,
) -> RResult<RString, RString> {
    let pre: Vec<String> = pre_scripts.iter().map(|s| s.to_string()).collect();

    match run_script_impl(script.as_str(), &pre, dispatcher) {
        Ok(stdout)  => ROk(RString::from(stdout)),
        Err(e)      => RErr(RString::from(e)),
    }
}

// ── Stdout thread-local ───────────────────────────────────────────────────

// Stored in Deno's OpState as Vec<String>; accessed via thread-local handle
// to avoid passing it through every op parameter.
//
// Each call to `run_script_impl` clears the buffer before use.

// ── Ops ───────────────────────────────────────────────────────────────────

/// Route a plugin call to whichever handler `sapphillon_core` registered.
///
/// JS call (generated by `get_pre_run_js`):
/// ```js
/// const result = Deno.core.ops.op_sapphillon_dispatch(opKey, argsJson);
/// ```
/// `opKey` — `"<package_id>::<function_name>"` for external plugins,
///           `"<function_id>"` for internal ones.
#[op2]
#[string]
fn op_sapphillon_dispatch(
    state: &mut OpState,
    #[string] op_key: String,
    #[string] args_json: String,
) -> Result<String, anyhow::Error> {
    let dispatcher = *state
        .try_borrow::<PluginDispatcher>()
        .ok_or_else(|| anyhow::anyhow!("PluginDispatcher not in OpState"))?;

    let result = dispatcher.call(
        RStr::from_str(&op_key),
        RStr::from_str(&args_json),
    );

    match result {
        ROk(s)  => Ok(s.into_string()),
        RErr(e) => Err(anyhow::anyhow!("{}", e)),
    }
}

/// Called by the JS `console` override installed as the first pre-script.
/// Appends the text to `Vec<String>` in OpState.
#[op2(fast)]
fn op_capture_stdout(state: &mut OpState, #[string] text: String) {
    if let Some(buf) = state.try_borrow_mut::<Vec<String>>() {
        buf.push(text);
    }
}

// ── Console override ──────────────────────────────────────────────────────

const CONSOLE_OVERRIDE_JS: &str = r#"
(function () {
    const _put = Deno.core.ops.op_capture_stdout;
    const _fmt = (...a) =>
        a.map(x => (typeof x === 'object' ? JSON.stringify(x) : String(x))).join(' ');
    globalThis.console = {
        log:   (...a) => _put(_fmt(...a)),
        info:  (...a) => _put('[INFO] '  + _fmt(...a)),
        warn:  (...a) => _put('[WARN] '  + _fmt(...a)),
        error: (...a) => _put('[ERROR] ' + _fmt(...a)),
        debug: (...a) => _put('[DEBUG] ' + _fmt(...a)),
    };
})();
"#;

// ── Core implementation ───────────────────────────────────────────────────

fn sapphillon_extension() -> Extension {
    Extension {
        name: "sapphillon",
        ops: std::borrow::Cow::Borrowed(&[
            op_sapphillon_dispatch(),
            op_capture_stdout(),
        ] as &[OpDecl]),
        ..Default::default()
    }
}

fn run_script_impl(
    script: &str,
    pre_scripts: &[String],
    dispatcher: PluginDispatcher,
) -> Result<String, String> {
    let mut runtime = JsRuntime::new(RuntimeOptions {
        extensions: vec![sapphillon_extension()],
        ..Default::default()
    });

    // Seed OpState.
    {
        let mut op_state = runtime.op_state().borrow_mut();
        op_state.put::<Vec<String>>(Vec::new()); // stdout buffer
        op_state.put::<PluginDispatcher>(dispatcher);
    }

    // Console override first.
    exec(&mut runtime, CONSOLE_OVERRIDE_JS, "<console-override>")?;

    // Plugin shims (pre-scripts).
    for (i, src) in pre_scripts.iter().enumerate() {
        exec(&mut runtime, src, &format!("<pre-script-{i}>"))?;
    }

    // Main workflow.
    exec(&mut runtime, script, "<workflow>")?;

    // Collect captured stdout.
    let stdout = runtime
        .op_state()
        .borrow()
        .borrow::<Vec<String>>()
        .join("\n");

    // Let the caller clean up the context.
    let op_state = runtime.op_state();
    let d = *op_state.borrow().borrow::<PluginDispatcher>();
    (d.drop_fn)(d.ctx);

    Ok(stdout)
}

fn exec(runtime: &mut JsRuntime, source: &str, specifier: &str) -> Result<(), String> {
    runtime
        .execute_script(specifier, FastString::from(source.to_string()))
        .map(|_| ())
        .map_err(|e| {
            // Downcast to JsError for the stack trace; fall back to Display.
            match e.downcast::<deno_core::error::JsError>() {
                Ok(js) => {
                    let mut msg = js.exception_message.clone();
                    if let Some(stack) = &js.stack {
                        msg.push('\n');
                        msg.push_str(stack);
                    }
                    msg
                }
                Err(e) => e.to_string(),
            }
        })
}
